webtalk_init -webtalk_dir /inner_space/shakti/correlator/c-class/fpga/project_1.sim/sim_1/behav/xsim/xsim.dir/mkTbSoc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 19 13:21:06 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "177482348_174144829_210597666_007" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0138e451-c586-4195-99a5-dbe05517e57a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aa415879349544c8a4224e13222fb792" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 2700X Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2199.086 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "199070 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "11.29_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "164408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2911490963 -regid "177482348_174144829_210597666_007" -xml /inner_space/shakti/correlator/c-class/fpga/project_1.sim/sim_1/behav/xsim/xsim.dir/mkTbSoc_behav/webtalk/usage_statistics_ext_xsim.xml -html /inner_space/shakti/correlator/c-class/fpga/project_1.sim/sim_1/behav/xsim/xsim.dir/mkTbSoc_behav/webtalk/usage_statistics_ext_xsim.html -wdm /inner_space/shakti/correlator/c-class/fpga/project_1.sim/sim_1/behav/xsim/xsim.dir/mkTbSoc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
