//
// Generated by Bluespec Compiler, version 2021.07-1-gaf77efcd (build af77efcd)
//
// On Tue Dec  7 15:48:14 IST 2021
//
//
// Ports:
// Name                         I/O  size props
// decoder_func_32                O    75
// decoder_func_32_inst           I    32
// decoder_func_32_csrs           I   199
// decoder_func_32_compressed     I     1
//
// Combinational paths from inputs to outputs:
//   (decoder_func_32_inst,
//    decoder_func_32_csrs,
//    decoder_func_32_compressed) -> decoder_func_32
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decoder_func_32(decoder_func_32_inst,
			      decoder_func_32_csrs,
			      decoder_func_32_compressed,
			      decoder_func_32);
  // value method decoder_func_32
  input  [31 : 0] decoder_func_32_inst;
  input  [198 : 0] decoder_func_32_csrs;
  input  decoder_func_32_compressed;
  output [74 : 0] decoder_func_32;

  // signals for module outputs
  wire [74 : 0] decoder_func_32;

  // remaining internal signals
  reg [10 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q8;
  reg [7 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9;
  reg [5 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q6,
	      _theResult_____9_snd__h3564,
	      _theResult_____9_snd__h3619;
  reg [3 : 0] CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q10,
	      CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q11,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12,
	      CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7,
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333,
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346,
	      IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d657,
	      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d369,
	      fn___1__h7433,
	      fn___1__h7495;
  reg [2 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q14;
  reg [1 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q13;
  reg CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q3,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q2,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q4,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5,
      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d173,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d495,
      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134,
      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187,
      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d250,
      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461,
      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d499,
      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321,
      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545;
  wire [47 : 0] IF_NOT_decoder_func_32_inst_BITS_1_TO_0_0_EQ_0_ETC___d669;
  wire [31 : 0] immediate_value___1__h4436,
		immediate_value__h51,
		instr_meta_immediate__h1013;
  wire [11 : 0] NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d579;
  wire [10 : 0] bit20_30__h49;
  wire [7 : 0] bit12_19__h48;
  wire [6 : 0] instr_meta_funct__h1014, temp1___1__h7165, temp1__h80;
  wire [5 : 0] _theResult_____9_snd__h3592, trapcause___1__h3614, x__h7168;
  wire [4 : 0] x__h21, x__h213, x__h482, x__h540;
  wire [3 : 0] IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d347,
	       IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d348,
	       IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d338,
	       IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d340,
	       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d361,
	       IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b10__ETC___d654,
	       IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d632,
	       fn___1__h7394,
	       fn___1__h7416;
  wire [2 : 0] IF_decoder_func_32_compressed_THEN_3_ELSE_2___d66;
  wire IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d313,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d537,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d548,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d120,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d180,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469,
       NOT_decoder_func_32_csrs_BIT_111_69_45_OR_NOT__ETC___d455,
       NOT_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_ETC___d542,
       NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201,
       address_valid___d311,
       bit31__h50,
       decoder_func_32_csrs_BIT_111_69_AND_decoder_fu_ETC___d181,
       decoder_func_32_csrs_BIT_99_42_AND_decoder_fun_ETC___d168,
       decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d175,
       decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d219,
       decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d217,
       decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136,
       decoder_func_32_inst_BITS_1_TO_0_0_EQ_0b11_1_O_ETC___d551,
       decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_51__ETC___d318,
       decoder_func_32_inst_BIT_25_95_EQ_INV_decoder__ETC___d242,
       decoder_func_32_inst_BIT_26_93_OR_decoder_func_ETC___d466,
       decoder_func_32_inst_BIT_27_45_OR_decoder_func_ETC___d647,
       valid_csr_access___d308;

  // value method decoder_func_32
  assign decoder_func_32 =
	     { x__h21,
	       x__h213,
	       x__h482,
	       x__h540,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q13,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q14,
	       decoder_func_32_inst[6:4] == 3'b100,
	       decoder_func_32_inst[6:2] == 5'b00001 ||
	       decoder_func_32_inst[6:4] == 3'b101 &&
	       decoder_func_32_inst[31:28] != 4'b1010 &&
	       decoder_func_32_inst[31:28] != 4'b1100 &&
	       decoder_func_32_inst[31:28] != 4'b1110 ||
	       decoder_func_32_inst[6:4] == 3'b100,
	       IF_NOT_decoder_func_32_inst_BITS_1_TO_0_0_EQ_0_ETC___d669 } ;

  // remaining internal signals
  module_valid_csr_access instance_valid_csr_access_1(.valid_csr_access_csr_addr(decoder_func_32_inst[31:20]),
						      .valid_csr_access_operand(decoder_func_32_inst[19:15]),
						      .valid_csr_access_operation(decoder_func_32_inst[13:12]),
						      .valid_csr_access_tvm(decoder_func_32_csrs[55]),
						      .valid_csr_access_prv(decoder_func_32_csrs[198:197]),
						      .valid_csr_access(valid_csr_access___d308));
  module_address_valid instance_address_valid_0(.address_valid_addr(decoder_func_32_inst[31:20]),
						.address_valid_misa(decoder_func_32_csrs[124:99]),
						.address_valid(address_valid___d311));
  assign IF_NOT_decoder_func_32_inst_BITS_1_TO_0_0_EQ_0_ETC___d669 =
	     { (decoder_func_32_inst[1:0] != 2'b11 &&
		IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321) ?
		 4'd6 :
		 IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d369,
	       (decoder_func_32_inst[6:2] == 5'b11100 &&
		decoder_func_32_inst[31:25] == 7'b0001001 &&
		decoder_func_32_inst[14:12] == 3'd0) ?
		 3'd5 :
		 ((decoder_func_32_inst[6:2] == 5'b01011) ?
		    3'd2 :
		    ((decoder_func_32_inst[12] &&
		      decoder_func_32_inst[6:2] == 5'b00011) ?
		       3'd4 :
		       ((!decoder_func_32_inst[12] &&
			 decoder_func_32_inst[6:2] == 5'b00011) ?
			  3'd3 :
			  ((decoder_func_32_inst[6:2] == 5'b01000 ||
			    decoder_func_32_inst[6:2] == 5'b01001 &&
			    decoder_func_32_csrs[104]) ?
			     3'd1 :
			     3'd0)))),
	       instr_meta_immediate__h1013,
	       instr_meta_funct__h1014,
	       decoder_func_32_inst[6:2] == 5'b00011 ||
	       decoder_func_32_inst_BITS_1_TO_0_0_EQ_0b11_1_O_ETC___d551 ||
	       decoder_func_32_inst[6:2] == 5'b11100 &&
	       decoder_func_32_inst[31:25] == 7'b0001001 &&
	       decoder_func_32_inst[14:12] == 3'd0,
	       1'd0 } ;
  assign IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d347 =
	     (NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211) ?
	       4'd8 :
	       4'd6 ;
  assign IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d348 =
	     (NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201 &&
	      (IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 ||
	       IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246)) ?
	       4'd8 :
	       4'd6 ;
  assign IF_decoder_func_32_compressed_THEN_3_ELSE_2___d66 =
	     decoder_func_32_compressed ? 3'd3 : 3'd2 ;
  assign IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d338 =
	     (decoder_func_32_csrs[111] &&
	      decoder_func_32_inst[31:25] == 7'd1) ?
	       4'd9 :
	       (IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d173 ?
		  4'd0 :
		  4'd6) ;
  assign IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d340 =
	     (decoder_func_32_csrs[111] &&
	      decoder_func_32_inst[31:25] == 7'd1 &&
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       !decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d175)) ?
	       4'd9 :
	       (IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d180 ?
		  4'd0 :
		  4'd6) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d313 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       decoder_func_32_inst[31:20] == 12'h002 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[112] ||
	       decoder_func_32_inst[31:20] == 12'h102 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[117] &&
	       (decoder_func_32_csrs[198:197] == 2'd3 ||
		decoder_func_32_csrs[198:197] == 2'd1 &&
		!decoder_func_32_csrs[57]) ||
	       decoder_func_32_inst[31:20] == 12'h302 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[198:197] == 2'd3 ||
	       ((decoder_func_32_inst[31:20] == 12'h105 &&
		 decoder_func_32_inst[19:15] == 5'd0 &&
		 decoder_func_32_inst[11:7] == 5'd0) ?
		  !decoder_func_32_csrs[56] ||
		  decoder_func_32_csrs[198:197] == 2'd3 :
		  decoder_func_32_inst[31:25] == 7'b0001001 &&
		  decoder_func_32_inst[11:7] == 5'd0 &&
		  (!decoder_func_32_csrs[55] ||
		   decoder_func_32_csrs[198:197] == 2'd3)) :
	       decoder_func_32_inst[14:12] != 3'd4 &&
	       valid_csr_access___d308 &&
	       address_valid___d311 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d361 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1 :
	       ((decoder_func_32_inst[14:12] != 3'd4 &&
		 valid_csr_access___d308 &&
		 address_valid___d311) ?
		  4'd5 :
		  4'd6) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d537 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       (decoder_func_32_inst[31:20] != 12'h002 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		!decoder_func_32_csrs[112]) &&
	       (decoder_func_32_inst[31:20] != 12'h102 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		!decoder_func_32_csrs[117] ||
		decoder_func_32_csrs[198:197] != 2'd3 &&
		(decoder_func_32_csrs[198:197] != 2'd1 ||
		 decoder_func_32_csrs[57])) &&
	       (decoder_func_32_inst[31:20] != 12'h302 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		decoder_func_32_csrs[198:197] != 2'd3) &&
	       ((decoder_func_32_inst[31:20] == 12'h105 &&
		 decoder_func_32_inst[19:15] == 5'd0 &&
		 decoder_func_32_inst[11:7] == 5'd0) ?
		  decoder_func_32_csrs[56] &&
		  decoder_func_32_csrs[198:197] != 2'd3 :
		  decoder_func_32_inst[31:25] != 7'b0001001 ||
		  decoder_func_32_inst[11:7] != 5'd0 ||
		  decoder_func_32_csrs[55] &&
		  decoder_func_32_csrs[198:197] != 2'd3) :
	       decoder_func_32_inst[14:12] == 3'd4 ||
	       !valid_csr_access___d308 ||
	       !address_valid___d311 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d548 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       decoder_func_32_inst[31:20] == 12'h002 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[112] ||
	       decoder_func_32_inst[31:20] == 12'h102 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[117] &&
	       (decoder_func_32_csrs[198:197] == 2'd3 ||
		decoder_func_32_csrs[198:197] == 2'd1 &&
		!decoder_func_32_csrs[57]) ||
	       decoder_func_32_inst[31:20] == 12'h302 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[198:197] == 2'd3 :
	       decoder_func_32_inst[14:12] != 3'd4 &&
	       valid_csr_access___d308 &&
	       address_valid___d311 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d120 =
	     (decoder_func_32_inst[14:12] == 3'd1) ?
	       decoder_func_32_inst[31:26] == 6'd0 :
	       decoder_func_32_inst[14:12] != 3'd5 ||
	       decoder_func_32_inst[31:26] == 6'd0 ||
	       decoder_func_32_inst[31:26] == 6'b010000 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d180 =
	     (decoder_func_32_inst[14:12] == 3'd1) ?
	       decoder_func_32_inst[31:25] == 7'b0 :
	       (decoder_func_32_inst[14:12] == 3'd0 ||
		decoder_func_32_inst[14:12] == 3'd5) &&
	       (decoder_func_32_inst[31:25] == 7'b0 ||
		decoder_func_32_inst[31:25] == 7'b0100000) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211 =
	     (decoder_func_32_inst[14:12] == 3'd7) ?
	       decoder_func_32_csrs[34:32] != 3'b101 &&
	       decoder_func_32_csrs[34:32] != 3'b110 :
	       decoder_func_32_inst[14:12] != 3'd5 &&
	       decoder_func_32_inst[14:12] != 3'b110 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469 =
	     (decoder_func_32_inst[14:12] == 3'd7) ?
	       decoder_func_32_csrs[34:32] == 3'b101 ||
	       decoder_func_32_csrs[34:32] == 3'b110 :
	       decoder_func_32_inst[14:12] == 3'd5 ||
	       decoder_func_32_inst[14:12] == 3'b110 ;
  assign IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b10__ETC___d654 =
	     (decoder_func_32_inst[6:5] == 2'b10 &&
	      decoder_func_32_csrs[104] | decoder_func_32_csrs[102]) ?
	       decoder_func_32_inst[5:2] :
	       ((decoder_func_32_inst[6:2] == 5'b01011) ?
		  { decoder_func_32_inst_BIT_27_45_OR_decoder_func_ETC___d647 ?
		      decoder_func_32_inst[29:27] :
		      decoder_func_32_inst[31:29],
		    decoder_func_32_inst_BIT_27_45_OR_decoder_func_ETC___d647 ||
		    decoder_func_32_inst[27] } :
		  4'd0) ;
  assign IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d632 =
	     decoder_func_32_inst[30] ? 4'b1011 : 4'b0101 ;
  assign NOT_decoder_func_32_csrs_BIT_111_69_45_OR_NOT__ETC___d455 =
	     (!decoder_func_32_csrs[111] ||
	      decoder_func_32_inst[31:25] != 7'd1 ||
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d175) &&
	     ((decoder_func_32_inst[14:12] == 3'd1) ?
		decoder_func_32_inst[31:25] != 7'b0 :
		decoder_func_32_inst[14:12] != 3'd0 &&
		decoder_func_32_inst[14:12] != 3'd5 ||
		decoder_func_32_inst[31:25] != 7'b0 &&
		decoder_func_32_inst[31:25] != 7'b0100000) ;
  assign NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d579 =
	     { decoder_func_32_inst[6:2] != 5'b01011 &&
	       ((decoder_func_32_inst[6:2] == 5'b11000) ?
		  decoder_func_32_inst[7] :
		  decoder_func_32_inst[6:2] != 5'b01101 &&
		  decoder_func_32_inst[6:2] != 5'b00101 &&
		  ((decoder_func_32_inst[6:2] == 5'b11011) ?
		     decoder_func_32_inst[20] :
		     decoder_func_32_inst[31])),
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q6,
	       (decoder_func_32_inst[6:2] == 5'b01011) ?
		 4'd0 :
		 ((decoder_func_32_inst[6:2] == 5'b01000 ||
		   decoder_func_32_inst[6:2] == 5'b01001 &&
		   decoder_func_32_csrs[104] ||
		   decoder_func_32_inst[6:2] == 5'b11000) ?
		    decoder_func_32_inst[11:8] :
		    CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7),
	       decoder_func_32_inst[6:2] != 5'b01011 &&
	       ((decoder_func_32_inst[6:2] == 5'b01000 ||
		 decoder_func_32_inst[6:2] == 5'b01001 &&
		 decoder_func_32_csrs[104]) ?
		  decoder_func_32_inst[7] :
		  decoder_func_32_inst[6:2] != 5'b11000 &&
		  decoder_func_32_inst[6:2] != 5'b01101 &&
		  decoder_func_32_inst[6:2] != 5'b00101 &&
		  decoder_func_32_inst[6:2] != 5'b11011 &&
		  decoder_func_32_inst[20]) } ;
  assign NOT_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_ETC___d542 =
	     decoder_func_32_inst[6:5] != 2'b11 ||
	     CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q4 ;
  assign NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201 =
	     !decoder_func_32_inst[26] &&
	     decoder_func_32_csrs[49:48] != 2'd0 &&
	     (!decoder_func_32_inst[25] && decoder_func_32_csrs[104] ||
	      decoder_func_32_inst[25] && decoder_func_32_csrs[102]) ;
  assign _theResult_____9_snd__h3592 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       _theResult_____9_snd__h3619 :
	       6'd2 ;
  assign bit12_19__h48 = {8{decoder_func_32_inst[31]}} ;
  assign bit20_30__h49 =
	     { bit12_19__h48,
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31] } ;
  assign bit31__h50 =
	     decoder_func_32_inst[6:2] != 5'b01011 &&
	     decoder_func_32_inst[31] ;
  assign decoder_func_32_csrs_BIT_111_69_AND_decoder_fu_ETC___d181 =
	     decoder_func_32_csrs[111] &&
	     decoder_func_32_inst[31:25] == 7'd1 &&
	     (decoder_func_32_inst[14:12] == 3'd0 ||
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d175) ||
	     IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d180 ;
  assign decoder_func_32_csrs_BIT_99_42_AND_decoder_fun_ETC___d168 =
	     decoder_func_32_csrs[99] &&
	     (decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_inst[14:12] == 3'd3) &&
	     (decoder_func_32_inst[31:27] == 5'b0 ||
	      decoder_func_32_inst[31:27] == 5'b00001 ||
	      decoder_func_32_inst[31:27] == 5'b00011 ||
	      decoder_func_32_inst[31:27] == 5'b00100 ||
	      decoder_func_32_inst[31:27] == 5'b01000 ||
	      decoder_func_32_inst[31:27] == 5'd12 ||
	      decoder_func_32_inst[31:27] == 5'd16 ||
	      decoder_func_32_inst[31:27] == 5'b10100 ||
	      decoder_func_32_inst[31:27] == 5'b11000 ||
	      decoder_func_32_inst[31:27] == 5'b11100 ||
	      decoder_func_32_inst[31:27] == 5'b00010 &&
	      decoder_func_32_inst[24:20] == 5'd0) ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d175 =
	     decoder_func_32_inst[14:12] <= 3'd3 ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d219 =
	     decoder_func_32_inst[14:12] < 3'd2 ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d217 =
	     decoder_func_32_inst[14:12] < 3'd3 ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136 =
	     decoder_func_32_inst[14:12] < 3'd4 ;
  assign decoder_func_32_inst_BITS_1_TO_0_0_EQ_0b11_1_O_ETC___d551 =
	     (decoder_func_32_inst[1:0] == 2'b11 ||
	      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545) &&
	     decoder_func_32_inst[6:5] == 2'b11 &&
	     decoder_func_32_inst[4:2] == 3'b100 &&
	     IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d548 ;
  assign decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_51__ETC___d318 =
	     decoder_func_32_inst[6:5] == 2'b11 &&
	     CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q2 ;
  assign decoder_func_32_inst_BIT_25_95_EQ_INV_decoder__ETC___d242 =
	     decoder_func_32_inst[25] == ~decoder_func_32_inst[20] ;
  assign decoder_func_32_inst_BIT_26_93_OR_decoder_func_ETC___d466 =
	     decoder_func_32_inst[26] ||
	     decoder_func_32_csrs[49:48] == 2'd0 ||
	     (decoder_func_32_inst[25] || !decoder_func_32_csrs[104]) &&
	     (!decoder_func_32_inst[25] || !decoder_func_32_csrs[102]) ;
  assign decoder_func_32_inst_BIT_27_45_OR_decoder_func_ETC___d647 =
	     decoder_func_32_inst[27] | decoder_func_32_inst[28] ;
  assign fn___1__h7394 = { 3'd1, decoder_func_32_inst[12] } ;
  assign fn___1__h7416 = { 1'b1, decoder_func_32_inst[14:12] } ;
  assign immediate_value___1__h4436 =
	     { 15'd0,
	       decoder_func_32_inst[19:15],
	       NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d579 } ;
  assign immediate_value__h51 =
	     { bit31__h50,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q8,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9,
	       NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d579 } ;
  assign instr_meta_funct__h1014 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321 ||
	      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545) ?
	       temp1___1__h7165 :
	       temp1__h80 ;
  assign instr_meta_immediate__h1013 =
	     decoder_func_32_inst_BITS_1_TO_0_0_EQ_0b11_1_O_ETC___d551 ?
	       immediate_value___1__h4436 :
	       immediate_value__h51 ;
  assign temp1___1__h7165 = { 1'd0, x__h7168 } ;
  assign temp1__h80 =
	     { IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d657,
	       ((decoder_func_32_inst[1:0] == 2'b11 ||
		 IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545) &&
		decoder_func_32_inst[6:5] == 2'b10 &&
		IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d250 &&
		decoder_func_32_inst[14:12] == 3'd7) ?
		 decoder_func_32_csrs[34:32] :
		 decoder_func_32_inst[14:12] } ;
  assign trapcause___1__h3614 =
	     (decoder_func_32_csrs[119] &&
	      decoder_func_32_csrs[198:197] == 2'd0) ?
	       6'd8 :
	       ((decoder_func_32_csrs[117] &&
		 decoder_func_32_csrs[198:197] == 2'd1) ?
		  6'd9 :
		  6'd11) ;
  assign x__h21 =
	     (decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:2] == 5'b00101 ||
	      decoder_func_32_inst[6:2] == 5'b11100 &&
	      decoder_func_32_inst[14]) ?
	       5'd0 :
	       decoder_func_32_inst[19:15] ;
  assign x__h213 =
	     (decoder_func_32_inst[6:2] == 5'b11100 &&
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[31:25] != 7'b0001001 ||
	      decoder_func_32_inst[6:4] == 3'b0 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:4] == 3'b001 ||
	      decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b11001 ||
	      decoder_func_32_inst[6:4] == 3'b101 &&
	      decoder_func_32_inst[30] &&
	      decoder_func_32_csrs[102] | decoder_func_32_csrs[104]) ?
	       5'd0 :
	       decoder_func_32_inst[24:20] ;
  assign x__h482 =
	     (decoder_func_32_inst[6:2] == 5'b11000 ||
	      decoder_func_32_inst[6:3] == 4'b0100 ||
	      decoder_func_32_inst[6:2] == 5'b00011) ?
	       5'd0 :
	       decoder_func_32_inst[11:7] ;
  assign x__h540 =
	     (decoder_func_32_inst[6:4] == 3'b100) ?
	       decoder_func_32_inst[31:27] :
	       5'd0 ;
  assign x__h7168 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321 ||
	      decoder_func_32_inst[6:5] == 2'b0 ||
	      decoder_func_32_inst[6:5] == 2'b01 ||
	      decoder_func_32_inst[6:5] == 2'b10) ?
	       6'd2 :
	       ((decoder_func_32_inst[6:5] == 2'b11) ?
		  _theResult_____9_snd__h3564 :
		  6'd2) ;
  always@(decoder_func_32_inst or
	  trapcause___1__h3614 or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0: _theResult_____9_snd__h3619 = trapcause___1__h3614;
      25'h0002000:
	  _theResult_____9_snd__h3619 =
	      (decoder_func_32_csrs[15] &&
	       decoder_func_32_csrs[198:197] == 2'd3 ||
	       decoder_func_32_csrs[14] &&
	       decoder_func_32_csrs[198:197] == 2'd1 ||
	       decoder_func_32_csrs[13] &&
	       decoder_func_32_csrs[198:197] == 2'd0) ?
		6'd49 :
		6'd3;
      default: _theResult_____9_snd__h3619 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst or _theResult_____9_snd__h3592)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b011: _theResult_____9_snd__h3564 = 6'd2;
      3'b100: _theResult_____9_snd__h3564 = _theResult_____9_snd__h3592;
      default: _theResult_____9_snd__h3564 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d173 =
	      decoder_func_32_inst[31:25] == 7'b0 ||
	      decoder_func_32_inst[31:25] == 7'b0100000;
      default: IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d173 =
		   decoder_func_32_inst[31:25] == 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d217 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d219)
  begin
    case (decoder_func_32_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211;
      5'b00100, 5'b10100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d217;
      5'b00101:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d219;
      5'b01011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211;
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
	      decoder_func_32_inst[24:21] == 4'b0 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211;
      5'b11100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       decoder_func_32_inst[14:12] == 3'd1);
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 =
		   decoder_func_32_inst[31:27] == 5'b11110 &&
		   decoder_func_32_inst[24:20] == 5'd0 &&
		   decoder_func_32_inst[14:12] == 3'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211 or
	  decoder_func_32_inst_BIT_25_95_EQ_INV_decoder__ETC___d242)
  begin
    case (decoder_func_32_inst[31:27])
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246 =
	      decoder_func_32_inst[24:21] == 4'b0001 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211;
      5'b11100, 5'b11110:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      decoder_func_32_inst[14:12] == 3'd0;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246 =
		   decoder_func_32_inst[31:27] == 5'b01000 &&
		   decoder_func_32_inst[24:21] == 4'b0 &&
		   IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211 &&
		   decoder_func_32_inst_BIT_25_95_EQ_INV_decoder__ETC___d242;
    endcase
  end
  always@(decoder_func_32_inst or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0, 25'h0002000:
	  CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1 = 4'd6;
      default: CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q1 =
		   (decoder_func_32_inst[31:20] == 12'h002 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[112] ||
		    decoder_func_32_inst[31:20] == 12'h102 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[117] &&
		    (decoder_func_32_csrs[198:197] == 2'd3 ||
		     decoder_func_32_csrs[198:197] == 2'd1 &&
		     !decoder_func_32_csrs[57]) ||
		    decoder_func_32_inst[31:20] == 12'h302 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[198:197] == 2'd3) ?
		     4'd5 :
		     ((decoder_func_32_inst[31:20] == 12'h105 &&
		       decoder_func_32_inst[19:15] == 5'd0 &&
		       decoder_func_32_inst[11:7] == 5'd0) ?
			((!decoder_func_32_csrs[56] ||
			  decoder_func_32_csrs[198:197] == 2'd3) ?
			   4'd7 :
			   4'd6) :
			((decoder_func_32_inst[31:25] == 7'b0001001 &&
			  decoder_func_32_inst[11:7] == 5'd0) ?
			   ((!decoder_func_32_csrs[55] ||
			     decoder_func_32_csrs[198:197] == 2'd3) ?
			      4'd1 :
			      4'd6) :
			   4'd6));
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d120)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134 =
	      decoder_func_32_inst[14:12] != 3'd7;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134 =
	      decoder_func_32_csrs[49:48] != 2'd0 &&
	      (decoder_func_32_csrs[104] &&
	       decoder_func_32_inst[14:12] == 3'd2 ||
	       decoder_func_32_csrs[102] &&
	       decoder_func_32_inst[14:12] == 3'd3);
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134 =
	      decoder_func_32_inst[14:12] == 3'd0 ||
	      decoder_func_32_inst[14:12] == 3'd1;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d120;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134 =
		   decoder_func_32_inst[4:2] == 3'b101 ||
		   decoder_func_32_inst[4:2] == 3'b110 &&
		   (decoder_func_32_inst[14:12] == 3'd0 ||
		    ((decoder_func_32_inst[14:12] == 3'd1) ?
		       decoder_func_32_inst[31:25] == 7'b0 :
		       decoder_func_32_inst[14:12] == 3'd5 &&
		       (decoder_func_32_inst[31:25] == 7'b0 ||
			decoder_func_32_inst[31:25] == 7'b0100000)));
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs_BIT_111_69_AND_decoder_fu_ETC___d181 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136 or
	  decoder_func_32_csrs or
	  decoder_func_32_csrs_BIT_99_42_AND_decoder_fun_ETC___d168 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d173)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187 =
	      decoder_func_32_csrs[104] &&
	      decoder_func_32_csrs[49:48] != 2'd0 &&
	      decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_csrs[102] &&
	      decoder_func_32_csrs[49:48] != 2'd0 &&
	      decoder_func_32_inst[14:12] == 3'd3;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187 =
	      decoder_func_32_csrs_BIT_99_42_AND_decoder_fun_ETC___d168;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187 =
	      decoder_func_32_csrs[111] &&
	      decoder_func_32_inst[31:25] == 7'd1 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d173;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187 =
		   decoder_func_32_inst[4:2] == 3'b101 ||
		   decoder_func_32_inst[4:2] == 3'b110 &&
		   decoder_func_32_csrs_BIT_111_69_AND_decoder_fu_ETC___d181;
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d250 =
	      NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d211;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d250 =
		   decoder_func_32_inst[4:2] == 3'b100 &&
		   NOT_decoder_func_32_inst_BIT_26_93_94_AND_NOT__ETC___d201 &&
		   (IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d235 ||
		    IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d246);
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d313)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q2 =
	      decoder_func_32_inst[14:12] != 3'd2 &&
	      decoder_func_32_inst[14:12] != 3'd3;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q2 =
	      decoder_func_32_inst[14:12] == 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q2 =
		   decoder_func_32_inst[4:2] == 3'b011 ||
		   decoder_func_32_inst[4:2] == 3'b100 &&
		   IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d313;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_51__ETC___d318 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d250)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d134;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d187;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d250;
      2'd3:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d321 =
	      decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_51__ETC___d318;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d217 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d219)
  begin
    case (decoder_func_32_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469;
      5'b00100, 5'b10100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d217;
      5'b00101:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d219;
      5'b01011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469;
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
	      decoder_func_32_inst[24:21] != 4'b0 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469;
      5'b11100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[14:12] != 3'd1;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 =
		   decoder_func_32_inst[31:27] != 5'b11110 ||
		   decoder_func_32_inst[24:20] != 5'd0 ||
		   decoder_func_32_inst[14:12] != 3'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469 or
	  decoder_func_32_inst_BIT_25_95_EQ_INV_decoder__ETC___d242)
  begin
    case (decoder_func_32_inst[31:27])
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d495 =
	      decoder_func_32_inst[24:21] != 4'b0001 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469;
      5'b11100, 5'b11110:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d495 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      decoder_func_32_inst[14:12] != 3'd0;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d495 =
		   decoder_func_32_inst[31:27] != 5'b01000 ||
		   decoder_func_32_inst[24:21] != 4'b0 ||
		   IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469 ||
		   !decoder_func_32_inst_BIT_25_95_EQ_INV_decoder__ETC___d242;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BIT_26_93_OR_decoder_func_ETC___d466 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d495 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d499 =
	      decoder_func_32_inst_BIT_26_93_OR_decoder_func_ETC___d466 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_7_ETC___d469;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d499 =
		   decoder_func_32_inst[4:2] != 3'b100 ||
		   decoder_func_32_inst_BIT_26_93_OR_decoder_func_ETC___d466 ||
		   IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d488 &&
		   IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d495;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q3 =
	      decoder_func_32_inst[31:25] != 7'b0 &&
	      decoder_func_32_inst[31:25] != 7'b0100000;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q3 =
		   decoder_func_32_inst[31:25] != 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_csrs_BIT_111_69_45_OR_NOT__ETC___d455 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136 or
	  decoder_func_32_csrs or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q3)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461 =
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461 =
	      (!decoder_func_32_csrs[104] ||
	       decoder_func_32_csrs[49:48] == 2'd0 ||
	       decoder_func_32_inst[14:12] != 3'd2) &&
	      (!decoder_func_32_csrs[102] ||
	       decoder_func_32_csrs[49:48] == 2'd0 ||
	       decoder_func_32_inst[14:12] != 3'd3);
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461 =
	      !decoder_func_32_csrs[99] ||
	      decoder_func_32_inst[14:12] != 3'd2 &&
	      decoder_func_32_inst[14:12] != 3'd3 ||
	      decoder_func_32_inst[31:27] != 5'b0 &&
	      decoder_func_32_inst[31:27] != 5'b00001 &&
	      decoder_func_32_inst[31:27] != 5'b00011 &&
	      decoder_func_32_inst[31:27] != 5'b00100 &&
	      decoder_func_32_inst[31:27] != 5'b01000 &&
	      decoder_func_32_inst[31:27] != 5'd12 &&
	      decoder_func_32_inst[31:27] != 5'd16 &&
	      decoder_func_32_inst[31:27] != 5'b10100 &&
	      decoder_func_32_inst[31:27] != 5'b11000 &&
	      decoder_func_32_inst[31:27] != 5'b11100 &&
	      (decoder_func_32_inst[31:27] != 5'b00010 ||
	       decoder_func_32_inst[24:20] != 5'd0);
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461 =
	      (!decoder_func_32_csrs[111] ||
	       decoder_func_32_inst[31:25] != 7'd1) &&
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q3;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461 =
		   decoder_func_32_inst[4:2] != 3'b101 &&
		   (decoder_func_32_inst[4:2] != 3'b110 ||
		    NOT_decoder_func_32_csrs_BIT_111_69_45_OR_NOT__ETC___d455);
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d537)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q4 =
	      decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_inst[14:12] == 3'd3;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q4 =
	      decoder_func_32_inst[14:12] != 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q4 =
		   decoder_func_32_inst[4:2] != 3'b011 &&
		   (decoder_func_32_inst[4:2] != 3'b100 ||
		    IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d537);
    endcase
  end
  always@(decoder_func_32_inst or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
	      decoder_func_32_inst[14:12] == 3'd7;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
	      decoder_func_32_csrs[49:48] == 2'd0 ||
	      (!decoder_func_32_csrs[104] ||
	       decoder_func_32_inst[14:12] != 3'd2) &&
	      (!decoder_func_32_csrs[102] ||
	       decoder_func_32_inst[14:12] != 3'd3);
      3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[14:12] != 3'd1;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
	      (decoder_func_32_inst[14:12] == 3'd1) ?
		decoder_func_32_inst[31:26] != 6'd0 :
		decoder_func_32_inst[14:12] == 3'd5 &&
		decoder_func_32_inst[31:26] != 6'd0 &&
		decoder_func_32_inst[31:26] != 6'b010000;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
		   decoder_func_32_inst[4:2] != 3'b101 &&
		   (decoder_func_32_inst[4:2] != 3'b110 ||
		    decoder_func_32_inst[14:12] != 3'd0 &&
		    ((decoder_func_32_inst[14:12] == 3'd1) ?
		       decoder_func_32_inst[31:25] != 7'b0 :
		       decoder_func_32_inst[14:12] != 3'd5 ||
		       decoder_func_32_inst[31:25] != 7'b0 &&
		       decoder_func_32_inst[31:25] != 7'b0100000));
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_ETC___d542 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d499)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d461;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d499;
      2'd3:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d545 =
	      NOT_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b11_ETC___d542;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01011, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q6 = 6'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q6 =
		   decoder_func_32_inst[30:25];
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7 = 4'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7 =
		   decoder_func_32_inst[24:21];
    endcase
  end
  always@(decoder_func_32_inst or bit20_30__h49)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q8 =
	      decoder_func_32_inst[30:20];
      5'b01011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q8 = 11'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q8 =
		   bit20_30__h49;
    endcase
  end
  always@(decoder_func_32_inst or bit12_19__h48)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 =
	      decoder_func_32_inst[19:12];
      5'b01011: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 = 8'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 =
		   bit12_19__h48;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d632)
  begin
    case (decoder_func_32_inst[14:12])
      3'd2: fn___1__h7433 = 4'b1100;
      3'd3: fn___1__h7433 = 4'b1110;
      3'd5:
	  fn___1__h7433 =
	      IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d632;
      default: fn___1__h7433 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d632)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0: fn___1__h7495 = decoder_func_32_inst[30] ? 4'b1010 : 4'b0;
      3'd2: fn___1__h7495 = 4'b1100;
      3'd3: fn___1__h7495 = 4'b1110;
      3'd5:
	  fn___1__h7495 =
	      IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d632;
      default: fn___1__h7495 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b10__ETC___d654 or
	  fn___1__h7433 or fn___1__h7495 or fn___1__h7416 or fn___1__h7394)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00100, 5'b00110:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d657 =
	      fn___1__h7433;
      5'b01100, 5'b01110:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d657 =
	      fn___1__h7495;
      5'b11000:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d657 =
	      decoder_func_32_inst[14] ? fn___1__h7416 : fn___1__h7394;
      default: IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d657 =
		   IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b10__ETC___d654;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd1:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q10 = 4'd1;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q10 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q10 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d120)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 =
	      (decoder_func_32_inst[14:12] == 3'd7) ? 4'd6 : 4'd1;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 =
	      (decoder_func_32_csrs[49:48] != 2'd0 &&
	       (decoder_func_32_csrs[104] &&
		decoder_func_32_inst[14:12] == 3'd2 ||
		decoder_func_32_csrs[102] &&
		decoder_func_32_inst[14:12] == 3'd3)) ?
		4'd1 :
		4'd6;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 =
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q10;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_1_ETC___d120 ?
		4'd0 :
		4'd6;
      3'b101:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 = 4'd0;
      3'b110:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 =
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       ((decoder_func_32_inst[14:12] == 3'd1) ?
		  decoder_func_32_inst[31:25] == 7'b0 :
		  decoder_func_32_inst[14:12] == 3'd5 &&
		  (decoder_func_32_inst[31:25] == 7'b0 ||
		   decoder_func_32_inst[31:25] == 7'b0100000))) ?
		4'd0 :
		4'd6;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 =
		   4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136 or
	  decoder_func_32_csrs or
	  decoder_func_32_csrs_BIT_99_42_AND_decoder_fun_ETC___d168 or
	  IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d338 or
	  IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d340)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d136 ? 4'd1 : 4'd6;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 =
	      (decoder_func_32_csrs[104] &&
	       decoder_func_32_csrs[49:48] != 2'd0 &&
	       decoder_func_32_inst[14:12] == 3'd2 ||
	       decoder_func_32_csrs[102] &&
	       decoder_func_32_csrs[49:48] != 2'd0 &&
	       decoder_func_32_inst[14:12] == 3'd3) ?
		4'd1 :
		4'd6;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 =
	      decoder_func_32_csrs_BIT_99_42_AND_decoder_fun_ETC___d168 ?
		4'd1 :
		4'd6;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 =
	      IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d338;
      3'b101:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 = 4'd0;
      3'b110:
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 =
	      IF_decoder_func_32_csrs_BIT_111_69_AND_decoder_ETC___d340;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 =
		   4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d347 or
	  IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d348)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q11 =
	      IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d347;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q11 =
	      IF_NOT_decoder_func_32_inst_BIT_26_93_94_AND_N_ETC___d348;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q11 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d361)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 =
	      (decoder_func_32_inst[14:12] != 3'd2 &&
	       decoder_func_32_inst[14:12] != 3'd3) ?
		4'd2 :
		4'd6;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 =
	      (decoder_func_32_inst[14:12] == 3'd0) ? 4'd4 : 4'd6;
      3'b011: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 = 4'd3;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d361;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q11 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d369 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d333;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d369 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_5_EQ_0b0_6_ETC___d346;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d369 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q11;
      2'b11:
	  IF_decoder_func_32_inst_BITS_6_TO_5_3_EQ_0b0_4_ETC___d369 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b11001, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q13 = 2'd1;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_1__ETC__q13 =
		   (decoder_func_32_inst[6:4] == 3'b100 ||
		    decoder_func_32_inst[6:4] == 3'b101 &&
		    decoder_func_32_inst[31:28] != 4'b1101 &&
		    decoder_func_32_inst[31:28] != 4'b1111) ?
		     2'd2 :
		     2'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_compressed_THEN_3_ELSE_2___d66)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00011, 5'b11001, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q14 =
	      IF_decoder_func_32_compressed_THEN_3_ELSE_2___d66;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b11_IF__ETC__q14 =
		   (decoder_func_32_inst[6:4] == 3'b001 ||
		    decoder_func_32_inst[6:2] == 5'b01101) ?
		     3'd1 :
		     ((decoder_func_32_inst[6:4] == 3'b101 &&
		       !decoder_func_32_inst[30] ||
		       decoder_func_32_inst[6:2] == 5'b01001 ||
		       decoder_func_32_inst[6:4] == 3'b100) ?
			3'd4 :
			3'd0);
    endcase
  end
endmodule  // module_decoder_func_32

