//
// Generated by Bluespec Compiler, version 2021.07-1-gaf77efcd (build af77efcd)
//
// On Tue Dec  7 15:48:10 IST 2021
//
//
// Ports:
// Name                         I/O  size props
// fn_decompress                  O    32
// fn_decompress_inst             I    16
//
// Combinational paths from inputs to outputs:
//   fn_decompress_inst -> fn_decompress
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_decompress(fn_decompress_inst,
			    fn_decompress);
  // value method fn_decompress
  input  [15 : 0] fn_decompress_inst;
  output [31 : 0] fn_decompress;

  // signals for module outputs
  wire [31 : 0] fn_decompress;

  // remaining internal signals
  wire [31 : 0] IF_fn_decompress_inst_BITS_15_TO_11_22_EQ_0b10_ETC___d338,
		IF_fn_decompress_inst_BITS_15_TO_11_22_EQ_0b10_ETC___d341,
		IF_fn_decompress_inst_BITS_15_TO_12_EQ_0b1000__ETC___d340,
		IF_fn_decompress_inst_BITS_15_TO_12_EQ_0b1001__ETC___d337,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b0_AND_ETC___d345,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b100_9_ETC___d355,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b101_3_ETC___d365,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b10_2__ETC___d343,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b10_2__ETC___d367,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b110_3_ETC___d335,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b111_0_ETC___d363,
		IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b1_2_A_ETC___d361,
		IF_fn_decompress_inst_BITS_15_TO_7_4_EQ_0b1110_ETC___d359;
  wire [11 : 0] SEXT_fn_decompress_inst_BIT_12_5_CONCAT_fn_dec_ETC___d79;
  wire [9 : 0] x__h1410, x__h4553;
  wire [8 : 0] x__h12674;
  wire [7 : 0] x__h12537, x__h1873;
  wire [6 : 0] x__h1714;
  wire [5 : 0] fn_decompress_inst_BIT_12_CONCAT_fn_decompress_ETC__q1;
  wire [3 : 0] x__h15197;
  wire [2 : 0] x__h15060, x__h2357;
  wire [1 : 0] x__h2177;
  wire fn_decompress_inst_BIT_10_AND_fn_decompress_in_ETC___d291,
       fn_decompress_inst_BIT_5_4_AND_fn_decompress_i_ETC___d302;

  // value method fn_decompress
  assign fn_decompress =
	     (fn_decompress_inst[15:12] == 4'b0001 &&
	      fn_decompress_inst[1:0] == 2'b0 ||
	      fn_decompress_inst[15:13] == 3'b0 &&
	      (fn_decompress_inst[11] || fn_decompress_inst[10] ||
	       fn_decompress_inst[9] ||
	       fn_decompress_inst[8] ||
	       fn_decompress_inst[7] ||
	       fn_decompress_inst[6] ||
	       fn_decompress_inst[5]) &&
	      fn_decompress_inst[1:0] == 2'b0) ?
	       { 2'd0, x__h1410, 10'd65, fn_decompress_inst[4:2], 7'd19 } :
	       ((fn_decompress_inst[15:13] == 3'b001 &&
		 fn_decompress_inst[1:0] == 2'b0) ?
		  { 4'd0,
		    x__h1873,
		    2'b01,
		    fn_decompress_inst[9:7],
		    5'b01101,
		    fn_decompress_inst[4:2],
		    7'd7 } :
		  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b10_2__ETC___d367) ;

  // remaining internal signals
  assign IF_fn_decompress_inst_BITS_15_TO_11_22_EQ_0b10_ETC___d338 =
	     (fn_decompress_inst[15:11] == 5'b10011 &&
	      fn_decompress_inst[6:0] == 7'b0000010 ||
	      fn_decompress_inst[15:12] == 4'b1001 &&
	      fn_decompress_inst_BIT_10_AND_fn_decompress_in_ETC___d291) ?
	       { 12'd0, fn_decompress_inst[11:7], 15'd231 } :
	       IF_fn_decompress_inst_BITS_15_TO_12_EQ_0b1001__ETC___d337 ;
  assign IF_fn_decompress_inst_BITS_15_TO_11_22_EQ_0b10_ETC___d341 =
	     (fn_decompress_inst[15:11] == 5'b10001 &&
	      fn_decompress_inst[6:0] == 7'b0000010 ||
	      fn_decompress_inst[15:12] == 4'b1000 &&
	      fn_decompress_inst_BIT_10_AND_fn_decompress_in_ETC___d291) ?
	       { 12'd0, fn_decompress_inst[11:7], 15'd103 } :
	       IF_fn_decompress_inst_BITS_15_TO_12_EQ_0b1000__ETC___d340 ;
  assign IF_fn_decompress_inst_BITS_15_TO_12_EQ_0b1000__ETC___d340 =
	     (fn_decompress_inst[15:12] == 4'b1000 &&
	      (fn_decompress_inst[6] && fn_decompress_inst[1:0] == 2'b10 ||
	       fn_decompress_inst_BIT_5_4_AND_fn_decompress_i_ETC___d302)) ?
	       { 7'b0,
		 fn_decompress_inst[6:2],
		 8'd0,
		 fn_decompress_inst[11:7],
		 7'd51 } :
	       ((fn_decompress_inst == 16'b1001000000000010) ?
		  32'd1048691 :
		  IF_fn_decompress_inst_BITS_15_TO_11_22_EQ_0b10_ETC___d338) ;
  assign IF_fn_decompress_inst_BITS_15_TO_12_EQ_0b1001__ETC___d337 =
	     (fn_decompress_inst[15:12] == 4'b1001 &&
	      (fn_decompress_inst[6] && fn_decompress_inst[1:0] == 2'b10 ||
	       fn_decompress_inst_BIT_5_4_AND_fn_decompress_i_ETC___d302)) ?
	       { 7'b0,
		 fn_decompress_inst[6:2],
		 fn_decompress_inst[11:7],
		 3'b0,
		 fn_decompress_inst[11:7],
		 7'd51 } :
	       ((fn_decompress_inst[15:13] == 3'b101 &&
		 fn_decompress_inst[1:0] == 2'b10) ?
		  { 3'd0,
		    x__h15197,
		    fn_decompress_inst[6:2],
		    8'd19,
		    fn_decompress_inst[11:10],
		    10'd39 } :
		  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b110_3_ETC___d335) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b0_AND_ETC___d345 =
	     (fn_decompress_inst[15:13] == 3'b0 &&
	      fn_decompress_inst[1:0] == 2'b10) ?
	       { 6'b0,
		 fn_decompress_inst[12],
		 fn_decompress_inst[6:2],
		 fn_decompress_inst[11:7],
		 3'b001,
		 fn_decompress_inst[11:7],
		 7'd19 } :
	       ((fn_decompress_inst[15:13] == 3'b001 &&
		 fn_decompress_inst[1:0] == 2'b10) ?
		  { 3'd0, x__h12674, 8'd19, fn_decompress_inst[11:7], 7'd7 } :
		  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b10_2__ETC___d343) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b100_9_ETC___d355 =
	     (fn_decompress_inst[15:13] == 3'b100 &&
	      fn_decompress_inst[11:10] == 2'b10 &&
	      fn_decompress_inst[1:0] == 2'b01) ?
	       { SEXT_fn_decompress_inst_BIT_12_5_CONCAT_fn_dec_ETC___d79,
		 2'b01,
		 fn_decompress_inst[9:7],
		 5'b11101,
		 fn_decompress_inst[9:7],
		 7'd19 } :
	       ((fn_decompress_inst[15:10] == 6'b100011 &&
		 fn_decompress_inst[6:5] == 2'b0 &&
		 fn_decompress_inst[1:0] == 2'b01) ?
		  { 9'b010000001,
		    fn_decompress_inst[4:2],
		    2'b01,
		    fn_decompress_inst[9:7],
		    5'b00001,
		    fn_decompress_inst[9:7],
		    7'd51 } :
		  ((fn_decompress_inst[15:10] == 6'b100011 &&
		    fn_decompress_inst[6:5] == 2'b01 &&
		    fn_decompress_inst[1:0] == 2'b01) ?
		     { 9'b000000001,
		       fn_decompress_inst[4:2],
		       2'b01,
		       fn_decompress_inst[9:7],
		       5'b10001,
		       fn_decompress_inst[9:7],
		       7'd51 } :
		     ((fn_decompress_inst[15:10] == 6'b100011 &&
		       fn_decompress_inst[6:5] == 2'b10 &&
		       fn_decompress_inst[1:0] == 2'b01) ?
			{ 9'b000000001,
			  fn_decompress_inst[4:2],
			  2'b01,
			  fn_decompress_inst[9:7],
			  5'b11001,
			  fn_decompress_inst[9:7],
			  7'd51 } :
			((fn_decompress_inst[15:10] == 6'b100011 &&
			  fn_decompress_inst[6:5] == 2'b11 &&
			  fn_decompress_inst[1:0] == 2'b01) ?
			   { 9'b000000001,
			     fn_decompress_inst[4:2],
			     2'b01,
			     fn_decompress_inst[9:7],
			     5'b11101,
			     fn_decompress_inst[9:7],
			     7'd51 } :
			   ((fn_decompress_inst[15:10] == 6'b100111 &&
			     fn_decompress_inst[6:5] == 2'b0 &&
			     fn_decompress_inst[1:0] == 2'b01) ?
			      { 9'b010000001,
				fn_decompress_inst[4:2],
				2'b01,
				fn_decompress_inst[9:7],
				5'b00001,
				fn_decompress_inst[9:7],
				7'd59 } :
			      ((fn_decompress_inst[15:10] == 6'b100111 &&
				fn_decompress_inst[6:5] == 2'b01 &&
				fn_decompress_inst[1:0] == 2'b01) ?
				 { 9'b000000001,
				   fn_decompress_inst[4:2],
				   2'b01,
				   fn_decompress_inst[9:7],
				   5'b00001,
				   fn_decompress_inst[9:7],
				   7'd59 } :
				 ((fn_decompress_inst[15:13] == 3'b101 &&
				   fn_decompress_inst[1:0] == 2'b01) ?
				    { fn_decompress_inst[12],
				      fn_decompress_inst[8],
				      fn_decompress_inst[10:9],
				      fn_decompress_inst[6],
				      fn_decompress_inst[7],
				      fn_decompress_inst[2],
				      fn_decompress_inst[11],
				      fn_decompress_inst[5:3],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      fn_decompress_inst[12],
				      12'd111 } :
				    ((fn_decompress_inst[15:13] == 3'b110 &&
				      fn_decompress_inst[1:0] == 2'b01) ?
				       { fn_decompress_inst[12],
					 fn_decompress_inst[12],
					 fn_decompress_inst[12],
					 fn_decompress_inst[12],
					 fn_decompress_inst[6:5],
					 fn_decompress_inst[2],
					 7'b0000001,
					 fn_decompress_inst[9:7],
					 3'b0,
					 fn_decompress_inst[11:10],
					 fn_decompress_inst[4:3],
					 fn_decompress_inst[12],
					 7'd99 } :
				       ((fn_decompress_inst[15:13] ==
					 3'b111 &&
					 fn_decompress_inst[1:0] == 2'b01) ?
					  { fn_decompress_inst[12],
					    fn_decompress_inst[12],
					    fn_decompress_inst[12],
					    fn_decompress_inst[12],
					    fn_decompress_inst[6:5],
					    fn_decompress_inst[2],
					    7'b0000001,
					    fn_decompress_inst[9:7],
					    3'b001,
					    fn_decompress_inst[11:10],
					    fn_decompress_inst[4:3],
					    fn_decompress_inst[12],
					    7'd99 } :
					  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b0_AND_ETC___d345))))))))) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b101_3_ETC___d365 =
	     (fn_decompress_inst[15:13] == 3'b101 &&
	      fn_decompress_inst[1:0] == 2'b0) ?
	       { 4'd0,
		 x__h2357,
		 2'b01,
		 fn_decompress_inst[4:2],
		 2'b01,
		 fn_decompress_inst[9:7],
		 3'b011,
		 fn_decompress_inst[11:10],
		 10'd39 } :
	       ((fn_decompress_inst[15:13] == 3'b110 &&
		 fn_decompress_inst[1:0] == 2'b0) ?
		  { 5'd0,
		    x__h2177,
		    2'b01,
		    fn_decompress_inst[4:2],
		    2'b01,
		    fn_decompress_inst[9:7],
		    3'b010,
		    fn_decompress_inst[11:10],
		    fn_decompress_inst[6],
		    9'd35 } :
		  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b111_0_ETC___d363) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b10_2__ETC___d343 =
	     (fn_decompress_inst[15:13] == 3'b010 &&
	      (fn_decompress_inst[11] || fn_decompress_inst[10] ||
	       fn_decompress_inst[9] ||
	       fn_decompress_inst[8] ||
	       fn_decompress_inst[7]) &&
	      fn_decompress_inst[1:0] == 2'b10) ?
	       { 4'd0, x__h12537, 8'd18, fn_decompress_inst[11:7], 7'd3 } :
	       ((fn_decompress_inst[15:13] == 3'b011 &&
		 fn_decompress_inst[1:0] == 2'b10) ?
		  { 3'd0, x__h12674, 8'd19, fn_decompress_inst[11:7], 7'd3 } :
		  IF_fn_decompress_inst_BITS_15_TO_11_22_EQ_0b10_ETC___d341) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b10_2__ETC___d367 =
	     (fn_decompress_inst[15:13] == 3'b010 &&
	      fn_decompress_inst[1:0] == 2'b0) ?
	       { 5'd0,
		 x__h1714,
		 2'b01,
		 fn_decompress_inst[9:7],
		 5'b01001,
		 fn_decompress_inst[4:2],
		 7'd3 } :
	       ((fn_decompress_inst[15:13] == 3'b011 &&
		 fn_decompress_inst[1:0] == 2'b0) ?
		  { 4'd0,
		    x__h1873,
		    2'b01,
		    fn_decompress_inst[9:7],
		    5'b01101,
		    fn_decompress_inst[4:2],
		    7'd3 } :
		  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b101_3_ETC___d365) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b110_3_ETC___d335 =
	     (fn_decompress_inst[15:13] == 3'b110 &&
	      fn_decompress_inst[1:0] == 2'b10) ?
	       { 4'd0,
		 x__h15060,
		 fn_decompress_inst[6:2],
		 8'd18,
		 fn_decompress_inst[11:9],
		 9'd35 } :
	       ((fn_decompress_inst[15:13] == 3'b111 &&
		 fn_decompress_inst[1:0] == 2'b10) ?
		  { 3'd0,
		    x__h15197,
		    fn_decompress_inst[6:2],
		    8'd19,
		    fn_decompress_inst[11:10],
		    10'd35 } :
		  32'd0) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b111_0_ETC___d363 =
	     (fn_decompress_inst[15:13] == 3'b111 &&
	      fn_decompress_inst[1:0] == 2'b0) ?
	       { 4'd0,
		 x__h2357,
		 2'b01,
		 fn_decompress_inst[4:2],
		 2'b01,
		 fn_decompress_inst[9:7],
		 3'b011,
		 fn_decompress_inst[11:10],
		 10'd35 } :
	       ((fn_decompress_inst[15:13] == 3'b0 &&
		 fn_decompress_inst[1:0] == 2'b01) ?
		  { SEXT_fn_decompress_inst_BIT_12_5_CONCAT_fn_dec_ETC___d79,
		    fn_decompress_inst[11:7],
		    3'b0,
		    fn_decompress_inst[11:7],
		    7'd19 } :
		  IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b1_2_A_ETC___d361) ;
  assign IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b1_2_A_ETC___d361 =
	     (fn_decompress_inst[15:13] == 3'b001 &&
	      (fn_decompress_inst[11] || fn_decompress_inst[10] ||
	       fn_decompress_inst[9] ||
	       fn_decompress_inst[8] ||
	       fn_decompress_inst[7]) &&
	      fn_decompress_inst[1:0] == 2'b01) ?
	       { SEXT_fn_decompress_inst_BIT_12_5_CONCAT_fn_dec_ETC___d79,
		 fn_decompress_inst[11:7],
		 3'b0,
		 fn_decompress_inst[11:7],
		 7'd27 } :
	       ((fn_decompress_inst[15:13] == 3'b010 &&
		 fn_decompress_inst[1:0] == 2'b01) ?
		  { SEXT_fn_decompress_inst_BIT_12_5_CONCAT_fn_dec_ETC___d79,
		    8'd0,
		    fn_decompress_inst[11:7],
		    7'd19 } :
		  IF_fn_decompress_inst_BITS_15_TO_7_4_EQ_0b1110_ETC___d359) ;
  assign IF_fn_decompress_inst_BITS_15_TO_7_4_EQ_0b1110_ETC___d359 =
	     (fn_decompress_inst[15:7] == 9'b011100010 &&
	      fn_decompress_inst[1:0] == 2'b01 ||
	      fn_decompress_inst[15:13] == 3'b011 &&
	      (fn_decompress_inst[11:6] == 6'b000101 &&
	       fn_decompress_inst[1:0] == 2'b01 ||
	       fn_decompress_inst[11:7] == 5'b00010 &&
	       (fn_decompress_inst[5] && fn_decompress_inst[1:0] == 2'b01 ||
		fn_decompress_inst[4] && fn_decompress_inst[1:0] == 2'b01 ||
		fn_decompress_inst[3] && fn_decompress_inst[1:0] == 2'b01 ||
		fn_decompress_inst[2:0] == 3'b101))) ?
	       { { {2{x__h4553[9]}}, x__h4553 }, 20'd65811 } :
	       ((fn_decompress_inst[15:11] == 5'b01111 &&
		 fn_decompress_inst[1:0] == 2'b01 ||
		 fn_decompress_inst[15:12] == 4'b0111 &&
		 fn_decompress_inst[10] &&
		 fn_decompress_inst[1:0] == 2'b01 ||
		 fn_decompress_inst[15:12] == 4'b0111 &&
		 fn_decompress_inst[9] &&
		 fn_decompress_inst[1:0] == 2'b01 ||
		 fn_decompress_inst[15:12] == 4'b0111 &&
		 !fn_decompress_inst[8] &&
		 fn_decompress_inst[1:0] == 2'b01 ||
		 fn_decompress_inst[15:12] == 4'b0111 &&
		 fn_decompress_inst[7] &&
		 fn_decompress_inst[1:0] == 2'b01 ||
		 fn_decompress_inst[15:13] == 3'b011 &&
		 (fn_decompress_inst[11] && fn_decompress_inst[6] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[10] && fn_decompress_inst[6] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[9] && fn_decompress_inst[6] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  !fn_decompress_inst[8] && fn_decompress_inst[6] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[7:6] == 2'b11 &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[11] && fn_decompress_inst[5] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[10] && fn_decompress_inst[5] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[9] && fn_decompress_inst[5] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  !fn_decompress_inst[8] && fn_decompress_inst[5] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[7] && fn_decompress_inst[5] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[11] && fn_decompress_inst[4] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[10] && fn_decompress_inst[4] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[9] && fn_decompress_inst[4] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  !fn_decompress_inst[8] && fn_decompress_inst[4] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[7] && fn_decompress_inst[4] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[11] && fn_decompress_inst[3] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[10] && fn_decompress_inst[3] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[9] && fn_decompress_inst[3] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  !fn_decompress_inst[8] && fn_decompress_inst[3] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  fn_decompress_inst[7] && fn_decompress_inst[3] &&
		  fn_decompress_inst[1:0] == 2'b01 ||
		  (fn_decompress_inst[11] || fn_decompress_inst[10] ||
		   fn_decompress_inst[9] ||
		   !fn_decompress_inst[8] ||
		   fn_decompress_inst[7]) &&
		  fn_decompress_inst[2:0] == 3'b101)) ?
		  { { {14{fn_decompress_inst_BIT_12_CONCAT_fn_decompress_ETC__q1[5]}},
		      fn_decompress_inst_BIT_12_CONCAT_fn_decompress_ETC__q1 },
		    fn_decompress_inst[11:7],
		    7'd55 } :
		  ((fn_decompress_inst[15:13] == 3'b100 &&
		    fn_decompress_inst[11:10] == 2'b0 &&
		    fn_decompress_inst[1:0] == 2'b01) ?
		     { 6'b0,
		       fn_decompress_inst[12],
		       fn_decompress_inst[6:2],
		       2'b01,
		       fn_decompress_inst[9:7],
		       5'b10101,
		       fn_decompress_inst[9:7],
		       7'd19 } :
		     ((fn_decompress_inst[15:13] == 3'b100 &&
		       fn_decompress_inst[11:10] == 2'b01 &&
		       fn_decompress_inst[1:0] == 2'b01) ?
			{ 6'b010000,
			  fn_decompress_inst[12],
			  fn_decompress_inst[6:2],
			  2'b01,
			  fn_decompress_inst[9:7],
			  5'b10101,
			  fn_decompress_inst[9:7],
			  7'd19 } :
			IF_fn_decompress_inst_BITS_15_TO_13_EQ_0b100_9_ETC___d355))) ;
  assign SEXT_fn_decompress_inst_BIT_12_5_CONCAT_fn_dec_ETC___d79 =
	     { {6{fn_decompress_inst_BIT_12_CONCAT_fn_decompress_ETC__q1[5]}},
	       fn_decompress_inst_BIT_12_CONCAT_fn_decompress_ETC__q1 } ;
  assign fn_decompress_inst_BIT_10_AND_fn_decompress_in_ETC___d291 =
	     fn_decompress_inst[10] &&
	     fn_decompress_inst[6:0] == 7'b0000010 ||
	     fn_decompress_inst[9] && fn_decompress_inst[6:0] == 7'b0000010 ||
	     fn_decompress_inst[8] && fn_decompress_inst[6:0] == 7'b0000010 ||
	     fn_decompress_inst[7:0] == 8'b10000010 ;
  assign fn_decompress_inst_BIT_12_CONCAT_fn_decompress_ETC__q1 =
	     { fn_decompress_inst[12], fn_decompress_inst[6:2] } ;
  assign fn_decompress_inst_BIT_5_4_AND_fn_decompress_i_ETC___d302 =
	     fn_decompress_inst[5] && fn_decompress_inst[1:0] == 2'b10 ||
	     fn_decompress_inst[4] && fn_decompress_inst[1:0] == 2'b10 ||
	     fn_decompress_inst[3] && fn_decompress_inst[1:0] == 2'b10 ||
	     fn_decompress_inst[2:0] == 3'b110 ;
  assign x__h12537 =
	     { fn_decompress_inst[3:2],
	       fn_decompress_inst[12],
	       fn_decompress_inst[6:4],
	       2'd0 } ;
  assign x__h12674 =
	     { fn_decompress_inst[4:2],
	       fn_decompress_inst[12],
	       fn_decompress_inst[6:5],
	       3'd0 } ;
  assign x__h1410 =
	     { fn_decompress_inst[10:7],
	       fn_decompress_inst[12:11],
	       fn_decompress_inst[5],
	       fn_decompress_inst[6],
	       2'd0 } ;
  assign x__h15060 = { fn_decompress_inst[8:7], fn_decompress_inst[12] } ;
  assign x__h15197 = { fn_decompress_inst[9:7], fn_decompress_inst[12] } ;
  assign x__h1714 =
	     { fn_decompress_inst[5],
	       fn_decompress_inst[12:10],
	       fn_decompress_inst[6],
	       2'd0 } ;
  assign x__h1873 =
	     { fn_decompress_inst[6:5], fn_decompress_inst[12:10], 3'd0 } ;
  assign x__h2177 = { fn_decompress_inst[5], fn_decompress_inst[12] } ;
  assign x__h2357 = { fn_decompress_inst[6:5], fn_decompress_inst[12] } ;
  assign x__h4553 =
	     { fn_decompress_inst[12],
	       fn_decompress_inst[4:3],
	       fn_decompress_inst[5],
	       fn_decompress_inst[2],
	       fn_decompress_inst[6],
	       4'd0 } ;
endmodule  // module_fn_decompress

