//
// Generated by Bluespec Compiler, version 2021.07-1-gaf77efcd (build af77efcd)
//
// On Mon Dec  6 11:47:46 IST 2021
//
//
// Ports:
// Name                         I/O  size props
// decode_word32                  O     1
// decode_word32_inst             I    32
// decode_word32_misa_c           I     1
//
// Combinational paths from inputs to outputs:
//   (decode_word32_inst, decode_word32_misa_c) -> decode_word32
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decode_word32(decode_word32_inst,
			    decode_word32_misa_c,
			    decode_word32);
  // value method decode_word32
  input  [31 : 0] decode_word32_inst;
  input  decode_word32_misa_c;
  output decode_word32;

  // signals for module outputs
  wire decode_word32;

  // value method decode_word32
  assign decode_word32 =
	     (decode_word32_misa_c && decode_word32_inst[1:0] != 2'b11) ?
	       decode_word32_inst[1:0] == 2'd1 &&
	       (decode_word32_inst[15:13] == 3'b001 ||
		decode_word32_inst[15:13] == 3'b100 &&
		decode_word32_inst[12:10] == 3'b111 &&
		!decode_word32_inst[6]) :
	       decode_word32_inst[6:2] == 5'b00110 ||
	       decode_word32_inst[6:2] == 5'b01110 ||
	       decode_word32_inst[6:5] == 2'b10 && !decode_word32_inst[25] ||
	       decode_word32_inst[6:3] == 4'b0101 && !decode_word32_inst[12] ;
endmodule  // module_decode_word32

